# Generated by Django 2.2.6 on 2019-10-14 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('mangoabout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mango.MangoAbout')),
            ],
        ),
    ]
