# Generated by Django 2.2.3 on 2019-10-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0002_mangoabout_inserted_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Name')),
                ('email', models.TextField(blank=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('inserted_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
