# Generated by Django 2.2.3 on 2019-10-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0003_test1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
    ]
