# Generated by Django 2.2.3 on 2019-10-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0005_mangoabout1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MangoAbout1',
            new_name='MangoAbout2',
        ),
    ]
