# Generated by Django 2.2.3 on 2019-10-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0006_auto_20191029_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MangoAbout2',
        ),
    ]
