# Generated by Django 2.2.3 on 2019-10-29 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0008_mangoabout_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangoabout',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
