# Generated by Django 2.2.3 on 2019-10-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0009_auto_20191029_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField()),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
