# Generated by Django 2.2.3 on 2019-10-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0010_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
