# Generated by Django 2.2.3 on 2019-10-30 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0012_auto_20191030_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangoabout',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
